return {
    estetics = {
        modSpoilers = {label = "", image = "", prop = "", weight = 4000, index = 0, category = 'Exterior',},
        modFrontBumper = {label = "", image = "", prop = "", weight = 4000, index = 1, category = 'Exterior',},
        modRearBumper = {label = "", image = "", prop = "", weight = 4000, index = 2, category = 'Exterior',},
        modSideSkirt = {label = "", image = "", prop = "", weight = 4000, index = 3, category = 'Exterior',},
        modExhaust = {label = "", image = "", prop = "", weight = 4000, index = 4, category = 'Exterior',},
        modFrame = {label = "", image = "", prop = "", weight = 4000, index = 5, category = 'Exterior',},
        modGrille = {label = "", image = "", prop = "", weight = 4000, index = 6, category = 'Exterior',},
        modHood = {label = "", image = "", prop = "", weight = 4000, index = 7, category = 'Exterior',},
        modFender = {label = "", image = "", prop = "", weight = 4000, index = 8, category = 'Exterior',},
        modRightFender = {label = "", image = "", prop = "", weight = 4000, index = 9, category = 'Exterior',},
        modRoof = {label = "", image = "", prop = "", weight = 4000, index = 10, category = 'Exterior',},
        modHorns = {label = "", image = "", prop = "", weight = 4000, index = 14, category = 'Exterior',},
        modSubwoofer = {label = "", image = "", prop = "", weight = 4000, index = 19, category = 'Exterior',},
        modHydraulics = {label = "", image = "", prop = "", weight = 4000, index = 21, category = 'Exterior',},
        modPlateHolder = {label = "", image = "", prop = "", weight = 4000, index = 25, category = 'Exterior',},
        modVanityPlate = {label = "", image = "", prop = "", weight = 4000, index = 26, category = 'Exterior',},
        modTrimA = {label = "", image = "", prop = "", weight = 4000, index = 27, category = 'Exterior',},
        modOrnaments = {label = "", image = "", prop = "", weight = 4000, index = 28, category = 'Exterior',},
        modDashboard = {label = "", image = "", prop = "", weight = 4000, index = 29, category = 'Exterior',},
        modDial = {label = "", image = "", prop = "", weight = 4000, index = 30, category = 'Exterior',},
        modDoorSpeaker = {label = "", image = "", prop = "", weight = 4000, index = 31, category = 'Exterior',},
        modSeats = {label = "", image = "", prop = "", weight = 4000, index = 32, category = 'Exterior',},
        modSteeringWheel = {label = "", image = "", prop = "", weight = 4000, index = 33, category = 'Exterior',},
        modShifterLeavers = {label = "", image = "", prop = "", weight = 4000, index = 34, category = 'Exterior',},
        modAPlate = {label = "", image = "", prop = "", weight = 4000, index = 35, category = 'Exterior',},
        modSpeakers = {label = "", image = "", prop = "", weight = 4000, index = 36, category = 'Exterior',},
        modTrunk = {label = "", image = "", prop = "", weight = 4000, index = 37, category = 'Exterior',},
        modHydrolic = {label = "", image = "", prop = "", weight = 4000, index = 38, category = 'Exterior',},
        modEngineBlock = {label = "", image = "", prop = "", weight = 4000, index = 39, category = 'Exterior',},
        modAirFilter = {label = "", image = "", prop = "", weight = 4000, index = 40, category = 'Exterior',},
        modStruts = {label = "", image = "", prop = "", weight = 4000, index = 41, category = 'Exterior',},
        modArchCover = {label = "", image = "", prop = "", weight = 4000, index = 42, category = 'Exterior',},
        modAerials = {label = "", image = "", prop = "", weight = 4000, index = 43, category = 'Exterior',},
        modTrimB = {label = "", image = "", prop = "", weight = 4000, index = 44, category = 'Exterior',},
        modTank = {label = "", image = "", prop = "", weight = 4000, index = 45, category = 'Exterior',},
        modWindows = {label = "", image = "", prop = "", weight = 4000, index = 46, category = 'Exterior',},
        modDoorR = {label = "", image = "", prop = "", weight = 4000, index = 47, category = 'Exterior',},
        modRoofLivery = {label = "", image = "", prop = "", weight = 4000, index = 49, category = 'Exterior',},
        modLightbar = {label = "", image = "", prop = "", weight = 4000, index = 50, category = 'Exterior',},
    },
    especial = {
        category = 'Vanity',
        modLivery = {label = "", image = "", prop = "", weight = 4000, index = 48, },
        modXenon = {label = "", image = "", prop = "", weight = 4000, index = 22,},
        neonEnabled = {label = "", image = "", prop = "", weight = 4000, index = 103 },
        windowTint = {label = "", image = "", prop = "", weight = 4000, index = 102 },
        plateIndex = {label = "", image = "", prop = "", weight = 4000, index = 100 },
    },
    wheels = {
        modFrontWheels = {label = "", image = "", prop = "", weight = 4000, index = 23, category = 'Wheels',},
        modBackWheels = {label = "", image = "", prop = "", weight = 4000, index = 24, category = 'Wheels',},
        modCustomTiresF = {},
        modCustomTiresR = {},
        modSmokeEnabled = {},
        tyreSmokeColor = {},
    },
    
    performance = {
        modEngine = {image = "", prop = "", weight = 4000, handling = {}, parts = {}},
        modBrakes = {image = "", prop = "", weight = 4000, handling = {}, parts = {}},
        modTransmission = {image = "", prop = "", weight = 4000, handling = {}, parts = {}},
        modSuspension = {image = "", prop = "", weight = 4000, handling = {}, parts = {}},
        modArmor = {image = "", prop = "", weight = 4000, handling = {}, parts = {}},
        modNitrous = {image = "", prop = "", weight = 4000, handling = {}, parts = {}},
        modTurbo = {image = "", prop = "", weight = 4000, handling = {}, parts = {}},
        modCustomTire = {},
    },
    colors = {
        color1 = {},
        color2 = {},
        pearlescentColor = {},
        interiorColor = {},
        dashboardColor = {},
        wheelColor = {},
    }
}