local mods = {
    [0] = {
        label = 'Spoilers',
        image = '',
        prop = 'imp_prop_impexp_spoiler_04a',
        weight = 4000,
        index = 0,
        category = 'Exterior',
    },
    [1] = {
        label = 'Front Bumper',
        image = '',
        prop = 'imp_prop_impexp_bumper_01a',
        weight = 6000,
        index = 1,
        category = 'Exterior',
    },
    [2] = {
        label = 'Rear Bumper',
        image = '',
        prop = 'imp_prop_impexp_bumper_03a',
        weight = 6000,
        index = 2,
        category = 'Exterior',
    },
    [3] = {
        label = 'Side Skirt',
        image = '',
        prop = 'imp_prop_impexp_bumper_01a',
        weight = 4000,
        index = 3,
        category = 'Exterior',
    },
    [4] = {
        label = 'Exhaust',
        image = '',
        prop = 'imp_prop_impexp_exhaust_01a',
        weight = 2000,
        index = 4,
        category = 'Exterior',
    },
    [5] = {
        label = 'Roll Cage',
        image = '',
        prop = 'imp_prop_impexp_rear_bars_01b',
        weight = 6000,
        index = 5,
        category = 'Interior',
    },
    [6] = {
        label = 'Grille',
        image = '',
        prop = '',
        weight = 2000,
        index = 6,
        category = 'Exterior',
    },
    [7] = {
        label = 'Hood',
        image = 'veh_exterior',
        prop = 'imp_prop_impexp_bonnet_02a',
        weight = 10000,
        index = 7,
        category = 'Exterior',
    },
    [8] = {
        label = 'Left Fenders',
        image = '',
        prop = 'imp_prop_impexp_car_panel_01a',
        weight = 6000,
        index = 8,
        category = 'Exterior',
    },
    [9] = {
        label = 'Right Fenders',
        image = '',
        prop = 'imp_prop_impexp_car_panel_01a',
        weight = 6000,
        index = 9,
        category = 'Exterior',
    },
    [10] = {
        label = 'Roof',
        image = '',
        prop = 'imp_prop_impexp_car_panel_01a',
        weight = 10000,
        index = 10,
        category = 'Exterior',
    },
    [14] = {
        label = 'Horn',
        image = '',
        prop = '',
        weight = 1000,
        index = 14,
        category = 'Cosmetic',
    },
    [19] = {
        label = 'Subwoofer',
        image = '',
        prop = '',
        weight = 3000,
        index = 19,
        category = 'Cosmetic',
    },
    [21] = {
        label = 'Hydraulics',
        image = '',
        prop = '',
        weight = 5000,
        index = 21,
        category = 'Cosmetic',
    },
    [23] = {
        label = 'Front Rims',
        image = 'veh_wheels',
        prop = 'imp_prop_impexp_wheel_03a',
        weight = 10000,
        index = 23,
        category = 'Exterior',
    },
    [24] = {
        label = 'Back Rims',
        image = 'veh_wheels',
        prop = 'imp_prop_impexp_wheel_03a',
        weight = 10000,
        index = 24,
        category = 'Exterior',
    },
    [25] = {
        label = 'Plate Holder',
        image = 'veh_plates',
        prop = 'p_num_plate_01',
        weight = 1000,
        index = 25,
        category = 'Cosmetic',
    },
    [26] = {
        label = 'Vanity Plates',
        image = 'veh_plates',
        prop = 'p_num_plate_01',
        weight = 500,
        index = 26,
        category = 'Cosmetic',
    },
    [27] = {
        label = 'Trim',
        image = '',
        prop = '',
        weight = 2000,
        index = 27,
        category = 'Cosmetic',
    },
    [28] = {
        label = 'Ornaments',
        image = '',
        prop = '',
        weight = 1000,
        index = 28,
        category = 'Cosmetic',
    },
    [29] = {
        label = 'Dashboard',
        image = '',
        prop = '',
        weight = 3000,
        index = 29,
        category = 'Interior',
    },
    [30] = {
        label = 'Dial',
        image = '',
        prop = '',
        weight = 1000,
        index = 30,
        category = 'Interior',
    },
    [31] = {
        label = 'Door Speaker',
        image = '',
        prop = '',
        weight = 2000,
        index = 31,
        category = 'Interior',
    },
    [32] = {
        label = 'Seats',
        image = '',
        prop = '',
        weight = 4000,
        index = 32,
        category = 'Interior',
    },
    [33] = {
        label = 'Steering Wheel',
        image = '',
        prop = '',
        weight = 1500,
        index = 33,
        category = 'Interior',
    },
    [34] = {
        label = 'Shifter Leavers',
        image = '',
        prop = '',
        weight = 1000,
        index = 34,
        category = 'Interior',
    },
    [35] = {
        label = 'Plaques',
        image = '',
        prop = '',
        weight = 500,
        index = 35,
        category = 'Interior',
    },
    [36] = {
        label = 'Speakers',
        image = '',
        prop = '',
        weight = 2000,
        index = 36,
        category = 'Interior',
    },
    [37] = {
        label = 'Trunk',
        image = '',
        prop = 'imp_prop_impexp_trunk_01a',
        weight = 8000,
        index = 37,
        category = 'Exterior',
    },
    [38] = {
        label = 'Hydraulic',
        image = '',
        prop = '',
        weight = 5000,
        index = 38,
        category = 'Cosmetic',
    },
    [39] = {
        label = 'Engine Block',
        image = '',
        prop = '',
        weight = 10000,
        index = 39,
        category = 'Cosmetic',
    },
    [40] = {
        label = 'Air Filter',
        image = '',
        prop = '',
        weight = 1000,
        index = 40,
        category = 'Cosmetic',
    },
    [41] = {
        label = 'Struts',
        image = '',
        prop = '',
        weight = 5000,
        index = 41,
        category = 'Cosmetic',
    },
    [42] = {
        label = 'Arch Cover',
        image = '',
        prop = '',
        weight = 5000,
        index = 42,
        category = 'Cosmetic',
    },
    [43] = {
        label = 'Aerials',
        image = '',
        prop = '',
        weight = 5000,
        index = 43,
        category = 'Cosmetic',
    },
    [44] = {
        label = 'Trim',
        image = '',
        prop = '',
        weight = 5000,
        index = 44,
        category = 'Cosmetic',
    },
    [45] = {
        label = 'Tank',
        image = '',
        prop = '',
        weight = 5000,
        index = 45,
        category = 'Cosmetic',
    },
    [46] = {
        label = 'Windows',
        image = '',
        prop = '',
        weight = 5000,
        index = 46,
        category = 'Cosmetic',
    },
    [47] = {
        label = 'Doors',
        image = '',
        prop = '',
        weight = 5000,
        index = 47,
        category = 'Cosmetic',
    },
}
local vanity = {
    [22] = {
        label = 'Xenon Color',
        image = '',
        prop = '',
        weight = 2000,
        index = 22,
        category = 'Vanity',
    },
    [48] = {
        label = 'Livery',
        image = '',
        prop = '',
        weight = 1000,
        index = 48,
        category = 'Vanity',
    },
    [100] = {
        label = 'Plate Style',
        image = '',
        prop = '',
        weight = 500,
        index = 100,
        category = 'Vanity',
    },
    [102] = {
        label = 'Window Tint',
        image = '',
        prop = '',
        weight = 500,
        index = 102,
        category = 'Vanity',
    },
    [103] = {
        label = 'Neon Color',
        image = '',
        prop = '',
        weight = 4000,
        index = 103,
        category = 'Vanity',
    },

}

return {mods, vanity}